"""Refresh the live "set as it stands" section of the session report.

    python scripts/update_report.py [REPORT_20260830.md]

Rewrites everything between the `## 0.` heading and the following `---` with
current numbers from `logs/runs.jsonl` plus a fresh auditor pass, leaving the
hand-written findings below untouched. Safe to run repeatedly.
"""
from __future__ import annotations

import collections
import datetime
import io
import json
import math
import contextlib
import statistics as st
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

TARGET_RUNS = 20
PREVIOUS = "**20.9** (+/-3.8) over 15 runs, best 33, act 2 in 5/15, dmg/floor 5.72"


def _runs():
    path = ROOT / "logs" / "runs.jsonl"
    if not path.exists():
        return []
    out = []
    for line in open(path, encoding="utf-8"):
        if line.strip():
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return out


def _auditor_summary() -> str:
    """Run the decision auditor and fold its output into a couple of lines."""
    try:
        from scripts import audit_decisions as A  # type: ignore
    except Exception:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "audit_decisions", ROOT / "scripts" / "audit_decisions.py"
        )
        A = importlib.util.module_from_spec(spec)
        with contextlib.redirect_stdout(io.StringIO()):
            spec.loader.exec_module(A)
    log = A._latest_log()
    if log is None:
        return "No decision log yet."
    findings = A.audit(log)
    total = sum(len(v) for v in findings.values())
    if not total:
        return f"`audit_decisions.py` flags **nothing** across `{log.name}`."
    parts = ", ".join(
        f"{kind} {len(items)}"
        for kind, items in sorted(findings.items(), key=lambda kv: -len(kv[1]))
    )
    return (
        f"`audit_decisions.py` flags **{total}** candidates across "
        f"`{log.name}`: {parts}."
    )


def build_section() -> str:
    rows = _runs()
    now = datetime.datetime.now()
    if not rows:
        body = "No runs recorded yet."
        return f"## 0. The set, as it stands — updated {now:%H:%M}\n\n{body}\n\n---\n\n"

    floors = [r.get("floor_reached", 0) for r in rows]
    act2 = sum(1 for r in rows if r.get("act_reached", 1) >= 2)
    lines = []
    for i, r in enumerate(rows, 1):
        kb = r.get("killed_by") or {}
        who = ", ".join(sorted({e.get("name", "?") for e in (kb.get("enemies") or [])}))
        lines.append(
            f"    {i:>2}. floor {r.get('floor_reached'):>2}  act {r.get('act_reached')}  "
            f"deck {r.get('deck_size'):>2}  {kb.get('state_type','?'):8} {who[:34]}"
        )

    moe = ""
    if len(floors) > 1:
        moe = f" (95% margin +/-{1.96 * st.stdev(floors) / math.sqrt(len(floors)):.1f})"

    killers = collections.Counter()
    for r in rows:
        kb = r.get("killed_by") or {}
        ens = kb.get("enemies") or []
        if ens:
            killers[", ".join(sorted({e.get("name", "?") for e in ens}))] += 1
    repeat = [f"{k} x{c}" for k, c in killers.most_common() if c > 1]
    repeat_line = (
        "\nRepeat killers so far: " + ", ".join(repeat) + ".\n" if repeat else ""
    )

    caveat = (
        "At this sample size nothing is conclusive — the margin is enormous."
        if len(rows) < 8
        else "Still short of the full set; read the margin, not the average."
    )

    return f"""## 0. The set, as it stands — updated {now:%H:%M}

**{len(rows)} of {TARGET_RUNS} complete.**

    floors: {', '.join(map(str, floors))}
    average {sum(floors)/len(floors):.1f}{moe}   best {max(floors)}   act 2 reached {act2}/{len(rows)}

{chr(10).join(lines)}
{repeat_line}
Previous set for comparison: {PREVIOUS}. {caveat} This section is
regenerated by `scripts/update_report.py`.

**Auditor status:** {_auditor_summary()}

---

"""


def main() -> None:
    report = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "REPORT_20260830.md"
    if not report.exists():
        print(f"No report at {report}")
        return
    text = report.read_text(encoding="utf-8")
    start = text.find("## 0.")
    if start == -1:
        print("No '## 0.' section to replace.")
        return
    end = text.find("---", text.find("\n", start))
    end = text.find("\n", end) + 1 if end != -1 else len(text)
    report.write_text(text[:start] + build_section() + text[end:], encoding="utf-8")
    rows = _runs()
    print(f"report refreshed: {len(rows)}/{TARGET_RUNS} runs")


if __name__ == "__main__":
    main()
